force-app/main/default/objects/Loan__c/fields/Gross_Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Gross_Loan_Amount__c</fullName>
    <label>Gross Loan Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Loan__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <label>Loan Term (Months)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/UthLoan.cls
public with sharing class UthLoan {
    public static Loan__c build(Id personAccountId){
        Loan__c aloan = new Loan__c(
            Gross_Loan_Amount__c = 300,
            Name = 'Test Loan',
            Term__c = 12,
            Date_Loan_Issued__c = System.today(),
            Account__c = personAccountId
        );
        return aloan;
    }

    public static List<Loan__c> getAll(){
        return Database.query('SELECT '+
            String.join(new List<String>(Loan__c.getSObjectType().getDescribe().fields.getMap().keySet()), ',') +
            ' FROM Loan__c ' + 
            ' ORDER BY Id'
        );
    }
}